### ISSUE TITLE
Run JACKS from fold change

### ISSUE THREAD

**Issue by peterpdu** [felicityallen/JACKS#14]
Hi,

Is there a way to use the JACKS API to run the analysis starting from a log2 fold change table (and a corresponding table of precomputed variances)? That is, to input an sgRNA by screen table, like the heatmap shown in Figure 1 of the paper.

Thanks,
Peter

**Comment by lp2** [comment]
Are you happy to import python code? The relevant function is infer_JACKS
in JACKS/jacks/jacks/jacks.py; it requires control and test data matrices
[copied below]. It would also be doable to expose this directly via command
line, but it's a bit of work.

  Leo

""" Main function from which to compute JACKS across a set of specified
genes
@param gene_index {gene: [list of row indexes for the gRNAs for that gene
in the testdata]}
@param testdata (num_total_grnas x num_conditions x 2) numpy array
containing the mean (idx 0) and estimated variance (idx 1 )
         of each median normalized log-fold change
@param ctrldata Either (num_total_grnas x num_conditions x 2) numpy array
containing the respective control measurements
         for each element of testdata OR a (num_total_grnas x 2) numpy
array containing a common control measurement to
         be used for all conditions.
@return {gene: y, tau, x1, x2, w1, w2}, the JACKS inference results for
each gene in the input gene_index"""
def infer_JACKS(gene_index, testdata, ctrldata, fixed_x=None, n_iter=50,
apply_w_hp=False):
    results = {}
    for gene in gene_index:
        Ig = gene_index[gene]
        if fixed_x is not None:
            gene_fixed_x = {'X1':fixed_x['X1'][Ig], 'X2':fixed_x['X2'][Ig]}
        else: gene_fixed_x = fixed_x
        if testdata.shape == ctrldata.shape: # each line has a matching
control:
            results[gene] = infer_JACKS_gene(testdata[Ig,:,0],
testdata[Ig,:,1], ctrldata[Ig,:,0], ctrldata[Ig,:,1], n_iter,
fixed_x=gene_fixed_x, apply_w_hp=apply_w_hp)
        else: # shared control
            results[gene] = infer_JACKS_gene(testdata[Ig,:,0],
testdata[Ig,:,1], ctrldata[Ig,0], ctrldata[Ig,1], n_iter,
fixed_x=gene_fixed_x, apply_w_hp=apply_w_hp)

    return results

**Comment by lp2** [comment]
Sorry, that should have been infer.py:
https://github.com/felicityallen/JACKS/blob/master/jacks/jacks/infer.py

""" Main function from which to compute JACKS across a set of specified
genes
@param gene_index {gene: [list of row indexes for the gRNAs for that gene
in the testdata]}
@param testdata (num_total_grnas x num_conditions x 2) numpy array
containing the mean (idx 0) and estimated variance (idx 1 )
of each median normalized log-fold change
@param ctrldata Either (num_total_grnas x num_conditions x 2) numpy array
containing the respective control measurements
for each element of testdata OR a (num_total_grnas x 2) numpy array
containing a common control measurement to
be used for all conditions.
@return {gene: y, tau, x1, x2, w1, w2}, the JACKS inference results for
each gene in the input gene_index"""
def inferJACKS(gene_index, testdata, ctrldata, fixed_x=None, n_iter=50,
apply_w_hp=False, w_only=False):
results = {}
for gene in gene_index:
Ig = gene_index[gene]
if fixed_x is not None:
gene_fixed_x = {'X1':fixed_x['X1'][Ig], 'X2':fixed_x['X2'][Ig]}
else: gene_fixed_x = fixed_x
if testdata.shape != ctrldata.shape: # each line has a matching control:
raise Exception('Expecting matched size between control and test data')
y, tau, x1, x2, w1, w2 = inferJACKSGene(testdata[Ig,:,0], testdata[Ig,:,1],
ctrldata[Ig,:,0], ctrldata[Ig,:,1], n_iter, fixed_x=gene_fixed_x, apply_w_hp
=apply_w_hp)
if w_only: results[gene] = (None, None, None, None, w1, w2)
else: results[gene] = (y, tau, x1, x2, w1, w2)
return results

**Comment by peterpdu** [comment]
Great, thank you!
