### ISSUE TITLE
run_jacks_reference.py use of createSampleSpec needs updating

### ISSUE THREAD

**Issue by johncthomas** [felicityallen/JACKS#2]
run_jacks_reference.py calls createSampleSpec from run_jacks.py missing ctrl_sample_or_hdr argument, and it doesn't expect the tuple return value. 

I got around this by adding fixed X parts of rj_reference.py to run_jacks.py, see attached, but also changed it to take arguments from within Python which might not suit everyone.

[jacks_front.py.zip](https://github.com/felicityallen/JACKS/files/2102439/jacks_front.py.zip)

**Comment by felicityallen** [comment]
Many apologies for this and thanks for pointing this out. This broke in the last commit due to changes to run_JACKS.py. I've now updated run_JACKS_reference.py to mirror those changes, so it should now be working again. Thanks!
