### ISSUE TITLE
data_err of zero with one replicate

### ISSUE THREAD

**Issue by johncthomas** [felicityallen/JACKS#3]
When there are no replicates the data error used in jacks.infer_JACKS_gene() is zero. I think the line `data_err[SP.isnan(data_err)] = 2.0` is supposed to prevent this, but `io_preprocess.calc_posterior_sd()` returns zeroes, not NaNs, with single reps.

**Comment by felicityallen** [comment]
Many thanks for pointing this out. It is now fixed, please sync to latest.

**Comment by johncthomas** [comment]
Thanks for the quick response!
