### ISSUE TITLE
p-values or FDR

### ISSUE THREAD

**Issue by jeslipp** [felicityallen/JACKS#9]
Thank you for providing this tool. I would be interested to know if the p-values reported in the output files are raw p-values or corrected p-values. I was unable to find a documentation of the output file and it was not clear to me from the methods in the paper. 

Thanks for your time!

**Comment by lp2** [comment]
To the best of my knowledge, the p-values are uncorrected, but the FDR
cutoffs are ; Felicity will know better. The relevant code is here:
https://github.com/felicityallen/JACKS/blob/master/jacks/jacks/jacks_io.py#L68
and
the relevant lines are 83 and 84 [JACKS posterior of w is evaluated against
non-essential genes, and FDRs calculated].

  Leo

**Comment by felicityallen** [comment]
Sorry for my slow response, what Leo said is correct.

**Comment by jeslipp** [comment]
Thank you for the clarification!
